### ISSUE TITLE
When I click load bot code it does not work.

### ISSUE THREAD

**Issue by CosmicWebServices** [MegaApuTurkUltra/ATC-3-Controller#2]

**Comment by MegaApuTurkUltra** [comment]
Console output would help, along with browser/OS version, etc

**Comment by CosmicWebServices** [comment]
OK `[Error] SyntaxError: Unexpected identifier 'canvas' (anonymous function) (index.js:10)` My browser / operating system: MacOS Macintosh X 10.10.5, Safari 9.1.1, Flash 22.0 (release 0)

**Comment by MegaApuTurkUltra** [comment]
You'll need an ES6-compatible browser. Try Mozilla Firefox or Google Chrome

**Comment by CosmicWebServices** [comment]
OK
